### ISSUE TITLE
Restructuring TODO LIST

### ISSUE THREAD

**Issue by ds84182** [ds84182/LuaVM#5]
- [ ] Put binary files in their own directory
- [x] Make LuaVM libraries export via return and not globals
- [ ] Expansive test system for bytecode and decompiler3
- [ ] Better README and Documentation
